# Generated by Django 5.0.2 on 2024-03-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0003_imagesetting_alter_generalsetting_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'ordering': ('name',), 'verbose_name': 'General Setting', 'verbose_name_plural': 'General Settings'},
        ),
        migrations.AlterModelOptions(
            name='imagesetting',
            options={'ordering': ('name',), 'verbose_name': 'Image Setting', 'verbose_name_plural': 'Image Settings'},
        ),
    ]
