# Generated by Django 5.0.2 on 2024-03-20 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0004_alter_generalsetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='percentage')),
                ('percentage', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='percentage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
