# Generated by Django 5.0.2 on 2024-03-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0005_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='name'),
        ),
    ]
