# Generated by Django 5.0.2 on 2024-03-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0006_alter_skill_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('name',), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
