# Generated by Django 5.0.2 on 2024-03-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0011_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('school_name', models.CharField(blank=True, default='', max_length=255, verbose_name='School Name')),
                ('school_location', models.CharField(blank=True, default='', max_length=255, verbose_name='School Location')),
                ('graduation_type', models.CharField(blank=True, default='', max_length=255, verbose_name='Graduation Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ('-start_date',),
            },
        ),
    ]
