# Generated by Django 5.0.2 on 2024-03-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0012_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('link', models.URLField(blank=True, default='', max_length=255, verbose_name='Link')),
                ('icon', models.URLField(blank=True, default='', max_length=255, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'ordering': ('link',),
            },
        ),
    ]
