# Generated by Django 5.0.2 on 2024-03-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0013_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Icon'),
        ),
    ]
