# Generated by Django 5.0.2 on 2024-03-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0015_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='This is variable of the settings', max_length=255, verbose_name='Slug'),
        ),
    ]
